version: "3"
services:
  medication:
    container_name: medication
    image: medication
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "42069:8080"
    environment:
      - DATA_DIR=/data
    env_file:
      - stack.env
    volumes:
      - /docker/appdata/medication/data:/data